name: Pipeline Builder

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: zulu
          cache: ${{ !env.ACT && 'gradle' || '' }}

      - name: Build/Test
        run: |
          ./gradlew build

      - name: Login to Google Cloud
        if: ${{ github.event_name != 'pull_request' }}
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GAR_JSON_KEY }}

      - name: Publish
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          ./gradlew publish
